# -*- coding: utf-8 -*-
"""class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLQdWFC1Aced2yfC4gBSb_idfB1Pztxp

# Class
"""

class Person:
  def __init__(self, name, blood_type):
        self.name = name
        self.blood_type = blood_type

  def introduce(self):
    print(f"Hello, I'm {self.name}!")
    print(f"My blood type is {self.blood_type}!")

  def greeting(self):
      print('Hello')

class SeongChan(Person):
  def swing_arm(self):
    print("swing arms~")

class ChiWan(Person):
  def swing_leg(self):
    print("swing legs~")

class SooHyun():
  def swing_neck(self):
    print("swing neck~")

class HyunSoo(Person):
  def swing_eye(self):
    print(swing eyes~)

seongchan = SeongChan("성찬", "A")
chiwan = ChiWan("치완", "O")

seongchan.introduce()
seongchan.greeting()
seongchan.swing_arm()

chiwan.introduce()
chiwan.greeting()
chiwan.swing_leg()

chiwan.introduce()

chiwan.greeting()

# 1. 클래스 안의 변수를 뭐라고 부를까요? - 멤버 변수 / 속성
# 2. 클래스 안의 함수를 뭐라고 부를까요? - 메서드